# Predictive Road Maintenance Using Machine Learning

## Phase 1a: Data Collection and Validation

### Objective
The goal of this phase is to collect, organize, and validate all datasets required for predicting future road maintenance needs. The datasets include historical NYC 311 road complaints, traffic volume, weather observations, and OpenStreetMap road network data. Each dataset is verified before preprocessing begins.

## Datasets Collected

1. NYC 311 Service Requests (2012–2019)
2. NYC 311 Service Requests (2020–2025)
3. NYC Historical Traffic Volume (2012–2025)
4. Historical Weather Data (2012–2025)

In [45]:
import pandas as pd

### Load the 311 service requests (2012–2019)

In [46]:
# Load the 311 service requests (2012–2019)

service_311_2012_2019 = pd.read_csv(
    "../data/raw/311/311_service_requests_2012_2019.csv",
  
)

C:\Users\riya_\AppData\Local\Temp\ipykernel_19168\2705588236.py:3: DtypeWarning: Columns (0: Additional Details, 1: Incident Zip, 2: Landmark, 3: Facility Type, 4: Due Date) have mixed types. Specify dtype option on import or set low_memory=False.
  service_311_2012_2019 = pd.read_csv(

In [47]:
# Display the first 5 rows

service_311_2012_2019.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Problem (formerly Complaint Type),Problem Detail (formerly Descriptor),Additional Details,Location Type,Incident Zip,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,45281580,12/31/2019 10:57:20 PM,01/03/2020 11:45:00 AM,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,10016.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.751179,-73.980460,POINT (-73.980459668033 40.751178934701)
1,45280607,12/31/2019 10:28:03 PM,01/03/2020 09:05:00 AM,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,10466.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.886883,-73.865380,POINT (-73.8653796102 40.886883279469)
2,45281122,12/31/2019 10:25:35 PM,01/02/2020 11:15:41 AM,DOT,Department of Transportation,Street Condition,Failed Street Repair,NaN,Street,10467.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.885630,-73.866055,POINT (-73.866054822462 40.885629741909)
3,45284307,12/31/2019 10:07:25 PM,01/02/2020 02:05:00 PM,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,10305.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.592083,-74.089241,POINT (-74.089241472319 40.592083476993)
4,45284237,12/31/2019 09:01:36 PM,01/02/2020 10:15:00 AM,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,10314.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.588955,-74.167590,POINT (-74.167590478318 40.588954675168)

In [48]:
# Check the dataset

service_311_2012_2019.info()

<class 'pandas.DataFrame'>
RangeIndex: 757037 entries, 0 to 757036
Data columns (total 44 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unique Key                            757037 non-null  int64
 1   Created Date                          757037 non-null  str
 2   Closed Date                           740523 non-null  str
 3   Agency                                757037 non-null  str
 4   Agency Name                           757037 non-null  str
 5   Problem (formerly Complaint Type)     757037 non-null  str
 6   Problem Detail (formerly Descriptor)  757037 non-null  str
 7   Additional Details                    19 non-null      str
 8   Location Type                         272520 non-null  str
 9   Incident Zip                          715992 non-null  object
 10  Incident Address                      483647 non-null  str
 11  Street Name                           483643 non-null  str
 12  Cross Street 1                        546008 non-null  str
 13  Cross Street 2                        544729 non-null  str
 14  Intersection Street 1                 286554 non-null  str
 15  Intersection Street 2                 285323 non-null  str
 16  Address Type                          720331 non-null  str
 17  City                                  710759 non-null  str
 18  Landmark                              10827 non-null   str
 19  Facility Type                         5 non-null       str
 20  Status                                757037 non-null  str
 21  Due Date                              233386 non-null  str
 22  Resolution Description                756873 non-null  str
 23  Resolution Action Updated Date        756709 non-null  str
 24  Community Board                       757036 non-null  str
 25  Council District                      710048 non-null  float64
 26  Police Precinct                       757037 non-null  str
 27  BBL                                   331494 non-null  float64
 28  Borough                               757036 non-null  str
 29  X Coordinate (State Plane)            706516 non-null  float64
 30  Y Coordinate (State Plane)            706516 non-null  float64
 31  Open Data Channel Type                757037 non-null  str
 32  Park Facility Name                    757037 non-null  str
 33  Park Borough                          757036 non-null  str
 34  Vehicle Type                          0 non-null       float64
 35  Taxi Company Borough                  0 non-null       float64
 36  Taxi Pick Up Location                 0 non-null       float64
 37  Bridge Highway Name                   0 non-null       float64
 38  Bridge Highway Direction              0 non-null       float64
 39  Road Ramp                             0 non-null       float64
 40  Bridge Highway Segment                0 non-null       float64
 41  Latitude                              706516 non-null  float64
 42  Longitude                             706516 non-null  float64
 43  Location                              706516 non-null  str
dtypes: float64(13), int64(1), object(1), str(29)
memory usage: 561.5+ MB

In [49]:
# Check the size

service_311_2012_2019.shape

(757037, 44)

In [50]:
# Display the column names

service_311_2012_2019.columns

Index(['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name',
       'Problem (formerly Complaint Type)',
       'Problem Detail (formerly Descriptor)', 'Additional Details',
       'Location Type', 'Incident Zip', 'Incident Address', 'Street Name',
       'Cross Street 1', 'Cross Street 2', 'Intersection Street 1',
       'Intersection Street 2', 'Address Type', 'City', 'Landmark',
       'Facility Type', 'Status', 'Due Date', 'Resolution Description',
       'Resolution Action Updated Date', 'Community Board', 'Council District',
       'Police Precinct', 'BBL', 'Borough', 'X Coordinate (State Plane)',
       'Y Coordinate (State Plane)', 'Open Data Channel Type',
       'Park Facility Name', 'Park Borough', 'Vehicle Type',
       'Taxi Company Borough', 'Taxi Pick Up Location', 'Bridge Highway Name',
       'Bridge Highway Direction', 'Road Ramp', 'Bridge Highway Segment',
       'Latitude', 'Longitude', 'Location'],
      dtype='str')

In [51]:
# Count missing values

service_311_2012_2019.isnull().sum()

Unique Key                                   0
Created Date                                 0
Closed Date                              16514
Agency                                       0
Agency Name                                  0
Problem (formerly Complaint Type)            0
Problem Detail (formerly Descriptor)         0
Additional Details                      757018
Location Type                           484517
Incident Zip                             41045
Incident Address                        273390
Street Name                             273394
Cross Street 1                          211029
Cross Street 2                          212308
Intersection Street 1                   470483
Intersection Street 2                   471714
Address Type                             36706
City                                     46278
Landmark                                746210
Facility Type                           757032
Status                                       0
Due Date                                523651
Resolution Description                     164
Resolution Action Updated Date             328
Community Board                              1
Council District                         46989
Police Precinct                              0
BBL                                     425543
Borough                                      1
X Coordinate (State Plane)               50521
Y Coordinate (State Plane)               50521
Open Data Channel Type                       0
Park Facility Name                           0
Park Borough                                 1
Vehicle Type                            757037
Taxi Company Borough                    757037
Taxi Pick Up Location                   757037
Bridge Highway Name                     757037
Bridge Highway Direction                757037
Road Ramp                               757037
Bridge Highway Segment                  757037
Latitude                                 50521
Longitude                                50521
Location                                 50521
dtype: int64

In [52]:
# Check for duplicate rows

service_311_2012_2019.duplicated().sum()

np.int64(0)

In [53]:
# Display all complaint types

service_311_2012_2019[
    "Problem (formerly Complaint Type)"
].value_counts()

Problem (formerly Complaint Type)
Street Condition        756748
DEP Street Condition       289
Name: count, dtype: int64

In [54]:
# Standardize the complaint type

service_311_2012_2019[
    "Problem (formerly Complaint Type)"
] = service_311_2012_2019[
    "Problem (formerly Complaint Type)"
].replace(
    "DEP Street Condition",
    "Street Condition"
)

In [55]:
# Verify the complaint types

service_311_2012_2019[
    "Problem (formerly Complaint Type)"
].value_counts()

Problem (formerly Complaint Type)
Street Condition    757037
Name: count, dtype: int64

In [56]:
# Check the earliest and latest complaint dates just to double check the data is within the expected range

service_311_2012_2019["Created Date"].min()

'01/01/2012 07:25:58 PM'

In [57]:
service_311_2012_2019["Created Date"].max()

'12/31/2019 12:50:44 AM'

### Load the 311 service requests (2020–2025)

In [58]:
# Load the 311 service requests (2020–2025)

service_311_2020_2025 = pd.read_csv(
    "../data/raw/311/311_service_requests_2020_2025.csv",

)

C:\Users\riya_\AppData\Local\Temp\ipykernel_19168\2333083596.py:3: DtypeWarning: Columns (0: Additional Details, 1: Bridge Highway Name, 2: Bridge Highway Direction, 3: Road Ramp, 4: Bridge Highway Segment) have mixed types. Specify dtype option on import or set low_memory=False.
  service_311_2020_2025 = pd.read_csv(

In [59]:
# Display the first 5 rows

service_311_2020_2025.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Problem (formerly Complaint Type),Problem Detail (formerly Descriptor),Additional Details,Location Type,Incident Zip,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,69548813,07/01/2026 02:33:34 AM,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11434.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.692542,-73.775523,POINT (-73.775523227602 40.692542231523)
1,69550342,07/01/2026 02:32:26 AM,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11417.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.681420,-73.833670,POINT (-73.833669804029 40.681420316262)
2,69550343,07/01/2026 02:32:01 AM,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11434.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.688181,-73.788678,POINT (-73.788677532142 40.688180983102)
3,69547324,07/01/2026 02:31:17 AM,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11415.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,69548814,07/01/2026 02:30:39 AM,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,NaN,11419.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
# Check the dataset

service_311_2020_2025.info()

<class 'pandas.DataFrame'>
RangeIndex: 505888 entries, 0 to 505887
Data columns (total 44 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unique Key                            505888 non-null  int64
 1   Created Date                          505888 non-null  str
 2   Closed Date                           486234 non-null  str
 3   Agency                                505888 non-null  str
 4   Agency Name                           505888 non-null  str
 5   Problem (formerly Complaint Type)     505888 non-null  str
 6   Problem Detail (formerly Descriptor)  490305 non-null  str
 7   Additional Details                    37 non-null      str
 8   Location Type                         205442 non-null  str
 9   Incident Zip                          495090 non-null  float64
 10  Incident Address                      399790 non-null  str
 11  Street Name                           399774 non-null  str
 12  Cross Street 1                        401521 non-null  str
 13  Cross Street 2                        401580 non-null  str
 14  Intersection Street 1                 310797 non-null  str
 15  Intersection Street 2                 310895 non-null  str
 16  Address Type                          450407 non-null  str
 17  City                                  431054 non-null  str
 18  Landmark                              143519 non-null  str
 19  Facility Type                         0 non-null       float64
 20  Status                                505888 non-null  str
 21  Due Date                              0 non-null       float64
 22  Resolution Description                504606 non-null  str
 23  Resolution Action Updated Date        504615 non-null  str
 24  Community Board                       501217 non-null  str
 25  Council District                      384793 non-null  float64
 26  Police Precinct                       505888 non-null  str
 27  BBL                                   199103 non-null  float64
 28  Borough                               501217 non-null  str
 29  X Coordinate (State Plane)            385935 non-null  str
 30  Y Coordinate (State Plane)            386041 non-null  str
 31  Open Data Channel Type                505888 non-null  str
 32  Park Facility Name                    505888 non-null  str
 33  Park Borough                          501217 non-null  str
 34  Vehicle Type                          0 non-null       float64
 35  Taxi Company Borough                  0 non-null       float64
 36  Taxi Pick Up Location                 0 non-null       float64
 37  Bridge Highway Name                   136 non-null     str
 38  Bridge Highway Direction              136 non-null     str
 39  Road Ramp                             130 non-null     str
 40  Bridge Highway Segment                130 non-null     str
 41  Latitude                              385895 non-null  float64
 42  Longitude                             385895 non-null  float64
 43  Location                              385895 non-null  str
dtypes: float64(10), int64(1), str(33)
memory usage: 384.8 MB

In [61]:
# Check the size

service_311_2020_2025.shape

(505888, 44)

In [62]:
# Check missing values

service_311_2020_2025.isnull().sum()

Unique Key                                   0
Created Date                                 0
Closed Date                              19654
Agency                                       0
Agency Name                                  0
Problem (formerly Complaint Type)            0
Problem Detail (formerly Descriptor)     15583
Additional Details                      505851
Location Type                           300446
Incident Zip                             10798
Incident Address                        106098
Street Name                             106114
Cross Street 1                          104367
Cross Street 2                          104308
Intersection Street 1                   195091
Intersection Street 2                   194993
Address Type                             55481
City                                     74834
Landmark                                362369
Facility Type                           505888
Status                                       0
Due Date                                505888
Resolution Description                    1282
Resolution Action Updated Date            1273
Community Board                           4671
Council District                        121095
Police Precinct                              0
BBL                                     306785
Borough                                   4671
X Coordinate (State Plane)              119953
Y Coordinate (State Plane)              119847
Open Data Channel Type                       0
Park Facility Name                           0
Park Borough                              4671
Vehicle Type                            505888
Taxi Company Borough                    505888
Taxi Pick Up Location                   505888
Bridge Highway Name                     505752
Bridge Highway Direction                505752
Road Ramp                               505758
Bridge Highway Segment                  505758
Latitude                                119993
Longitude                               119993
Location                                119993
dtype: int64

In [63]:
# Check for duplicate rows

service_311_2020_2025.duplicated().sum()

np.int64(0)

In [64]:
# Display all complaint types

service_311_2020_2025[
    "Problem (formerly Complaint Type)"
].value_counts()

Problem (formerly Complaint Type)
Street Condition             489654
Homeless Street Condition     15583
DEP Street Condition            651
Name: count, dtype: int64

In [65]:
# Standardize the complaint type

service_311_2020_2025[
    "Problem (formerly Complaint Type)"
] = service_311_2020_2025[
    "Problem (formerly Complaint Type)"
].replace(
    "DEP Street Condition",
    "Street Condition"
)

In [66]:
# Verify the complaint types

service_311_2020_2025[
    "Problem (formerly Complaint Type)"
].value_counts()

Problem (formerly Complaint Type)
Street Condition             490305
Homeless Street Condition     15583
Name: count, dtype: int64

In [67]:
# Check the earliest complaint date

service_311_2020_2025["Created Date"].min()

'01/01/2020 01:05:32 PM'

In [68]:
# Check the latest complaint date

service_311_2020_2025["Created Date"].max()

'12/31/2025 12:56:01 PM'

### Load Traffic Volume Dataset

In [69]:
# Load the traffic volume dataset

traffic_volume = pd.read_csv(
    "../data/raw/traffic/traffic_volume_2012_2025.csv",
)

In [70]:
# Display the first 5 rows

traffic_volume.head()

,ID,SegmentID,Roadway Name,From,To,Direction,Date,12:00-1:00 AM,1:00-2:00AM,2:00-3:00AM,...,2:00-3:00PM,3:00-4:00PM,4:00-5:00PM,5:00-6:00PM,6:00-7:00PM,7:00-8:00PM,8:00-9:00PM,9:00-10:00PM,10:00-11:00PM,11:00-12:00AM
0,1,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/09/2012,20,10,11,...,104,105,147,120,91,83,74,49,42,42
1,2,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/10/2012,21,16,8,...,102,98,133,131,95,73,70,63,42,35
2,3,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/11/2012,27,14,6,...,115,115,130,143,106,89,68,64,56,43
3,4,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/12/2012,22,7,7,...,71,127,122,144,122,76,64,58,64,43
4,5,15540,BEACH STREET,UNION PLACE,VAN DUZER STREET,NB,01/13/2012,31,17,7,...,113,126,133,135,102,106,58,58,55,54

In [71]:
# Check the dataset

traffic_volume.info()

<class 'pandas.DataFrame'>
RangeIndex: 42756 entries, 0 to 42755
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             42756 non-null  int64
 1   SegmentID      42756 non-null  int64
 2   Roadway Name   42756 non-null  str
 3   From           42756 non-null  str
 4   To             42756 non-null  str
 5   Direction      42756 non-null  str
 6   Date           42756 non-null  str
 7   12:00-1:00 AM  42752 non-null  str
 8   1:00-2:00AM    42752 non-null  str
 9   2:00-3:00AM    42752 non-null  str
 10  3:00-4:00AM    42752 non-null  str
 11  4:00-5:00AM    42752 non-null  str
 12  5:00-6:00AM    42752 non-null  str
 13  6:00-7:00AM    42752 non-null  str
 14  7:00-8:00AM    42752 non-null  str
 15  8:00-9:00AM    42752 non-null  str
 16  9:00-10:00AM   42752 non-null  str
 17  10:00-11:00AM  42753 non-null  str
 18  11:00-12:00PM  42755 non-null  str
 19  12:00-1:00PM   42503 non-null  str
 20  1:00-2:00PM    42503 non-null  str
 21  2:00-3:00PM    42503 non-null  str
 22  3:00-4:00PM    42503 non-null  str
 23  4:00-5:00PM    42503 non-null  str
 24  5:00-6:00PM    42503 non-null  str
 25  6:00-7:00PM    42503 non-null  str
 26  7:00-8:00PM    42503 non-null  str
 27  8:00-9:00PM    42503 non-null  str
 28  9:00-10:00PM   42503 non-null  str
 29  10:00-11:00PM  42503 non-null  str
 30  11:00-12:00AM  42503 non-null  str
dtypes: int64(2), str(29)
memory usage: 15.2 MB

In [72]:
# Check the size 

traffic_volume.shape

(42756, 31)

In [73]:
# Check missing values

traffic_volume.isnull().sum()

ID                 0
SegmentID          0
Roadway Name       0
From               0
To                 0
Direction          0
Date               0
12:00-1:00 AM      4
1:00-2:00AM        4
2:00-3:00AM        4
3:00-4:00AM        4
4:00-5:00AM        4
5:00-6:00AM        4
6:00-7:00AM        4
7:00-8:00AM        4
8:00-9:00AM        4
9:00-10:00AM       4
10:00-11:00AM      3
11:00-12:00PM      1
12:00-1:00PM     253
1:00-2:00PM      253
2:00-3:00PM      253
3:00-4:00PM      253
4:00-5:00PM      253
5:00-6:00PM      253
6:00-7:00PM      253
7:00-8:00PM      253
8:00-9:00PM      253
9:00-10:00PM     253
10:00-11:00PM    253
11:00-12:00AM    253
dtype: int64

In [74]:
# Check for duplicate rows

traffic_volume.duplicated().sum()

np.int64(0)

In [75]:
# Check the earliest traffic date

traffic_volume["Date"].min()

'01/08/2012'

In [76]:
# Check the latest traffic date

traffic_volume["Date"].max()

'12/13/2020'

In [77]:
# Display the most common roadway names

traffic_volume["Roadway Name"].value_counts().head()

Roadway Name
BROADWAY            473
Broadway            387
3 AVENUE            324
LINDEN BOULEVARD    212
5 AVENUE            204
Name: count, dtype: int64

### Load the Open Meteo Weather Dataset

In [78]:
# Load the weather dataset

weather = pd.read_csv(
    "../data/raw/weather/open_meteo_weather_2012_2025.csv",

)

In [79]:
# Display the first 5 rows

weather.head()

,time,temperature_2m (°F),precipitation (inch),snowfall (inch),snow_depth (ft),weather_code (wmo code),wind_speed_10m (mp/h)
0,2012-01-01T00:00,39.6,0.0,0.0,0.0,0,8.7
1,2012-01-01T01:00,39.1,0.0,0.0,0.0,0,7.8
2,2012-01-01T02:00,38.6,0.0,0.0,0.0,0,7.5
3,2012-01-01T03:00,38.7,0.0,0.0,0.0,0,7.1
4,2012-01-01T04:00,38.2,0.0,0.0,0.0,0,6.0

In [80]:
# Check the dataset 

weather.info()

<class 'pandas.DataFrame'>
RangeIndex: 122736 entries, 0 to 122735
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   time                     122736 non-null  str
 1   temperature_2m (°F)      122736 non-null  float64
 2   precipitation (inch)     122736 non-null  float64
 3   snowfall (inch)          122736 non-null  float64
 4   snow_depth (ft)          122736 non-null  float64
 5   weather_code (wmo code)  122736 non-null  int64
 6   wind_speed_10m (mp/h)    122736 non-null  float64
dtypes: float64(5), int64(1), str(1)
memory usage: 8.4 MB

In [81]:
# Check the size 

weather.shape

(122736, 7)

In [82]:
# Check for missing values 

weather.isnull().sum()

time                       0
temperature_2m (°F)        0
precipitation (inch)       0
snowfall (inch)            0
snow_depth (ft)            0
weather_code (wmo code)    0
wind_speed_10m (mp/h)      0
dtype: int64

In [83]:
# Check for duplicate rows 

weather.duplicated().sum()

np.int64(0)

In [84]:
# Check the earliest weather date 

weather["time"].min()

'2012-01-01T00:00'

In [85]:
# Check the latest weather date 

weather["time"].max()

'2025-12-31T23:00'

In [86]:
# Display the weather columns 

weather.columns

Index(['time', 'temperature_2m (°F)', 'precipitation (inch)',
       'snowfall (inch)', 'snow_depth (ft)', 'weather_code (wmo code)',
       'wind_speed_10m (mp/h)'],
      dtype='str')

## Phase 1A Summary

The required datasets for this project were collected from publicly available New York City Open Data sources. The selected datasets include 311 road maintenance complaints, historical weather observations, and traffic volume data. These datasets provide the foundation for predicting future road maintenance risk by combining infrastructure, environmental, and traffic-related information.